install.packages("forecast")
install.packages('aTSA')
install.packages('fUnitRoots')
install.packages('rugarch')
library(changepoint)
library(strucchange)
library(tidyverse)
library(lubridate)
library(readxl)
library(forecast)
library(aTSA)
library(fUnitRoots)
library(rugarch)
r<-ts(week_collection$r)
plot.ts(r)
acf(r, lag.max = 20)
pacf(r, lag.max = 20)
hist(r)
dum=c(rep(0,60),rep(1,25),rep(0,64))
auto.arima(r, seasonal=FALSE, stationary= TRUE,xreg = dum,ic=c('aic'),trace = TRUE)
rarima<- arima(r, order=c(1,0,1),xreg = dum)
acf(rarima$residuals)
rarima
plot(rarima$residuals)
at<-rarima$residuals-mean(rarima$residuals)
Box.test(at^2,lag=90,type = "Ljung")
arch.test(rarima)
rfor<-predict(rarima, newxreg=dumf,n.ahead=5)
rfor
ts.plot(r,rfor$pred)

