install.packages("forecast")
install.packages('aTSA')
install.packages('fUnitRoots')
install.packages('rugarch')
install.packages('fGarch')
install.packages('xts')
install.packages('tseries')
library(xts)
library(changepoint)
library(strucchange)
library(tidyverse)
library(lubridate)
library(readxl)
library(forecast)
library(aTSA)
library(fUnitRoots)
library(rugarch)
library(tseries)
library(fGarch)
r<-ts(collection$r, frequency=1)
plot.ts(r)
hist(r)
acf
acf(r, lag.max = 200)
pacf(r, lag.max = 200)
dat <- tibble(ylag0 = r, ylag1 = lag(r))
dat = drop_na(dat)
qlr <- Fstats(ylag0 ~ ylag1, data = dat)
breakpoints(qlr)

auto.arima(r,stationary=TRUE)
rarima<- arima(r, order=c(2,0,2),include.mean = FALSE)
summary(rarima)
plot(rarima$residuals)
acf(rarima$residuals, lag.max = 200)
pacf(rarima$residuals, lag.max = 200)
arch.test(rarima)
garch_spec <- ugarchspec(mean.model = list(armaOrder = c(1,1), include.mean = TRUE), 
                         variance.model = list(model = "sGARCH", garchOrder = c(1,1)))
garch_fit <- ugarchfit(spec = garch_spec, data = r)
garch_fit
garch_fore <- ugarchforecast(garch_fit)
garch_fore
rfor = predict(rarima,10)
rfor

